#
# Make exe plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sasahipa.com>
#
# $Id: Makefile,v 1.3 2004-07-31 22:55:18 vincentp Exp $
#

SUBDIRS = display entrylist net dhcp

include ../../Makefile.inc
