#
# Make exe plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sasahipa.com>
#
# $Id: Makefile,v 1.1 2002-09-25 21:36:44 vincentp Exp $
#

SUBDIRS = display

include ../../Makefile.inc
