#
# Make exe plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sasahipa.com>
#
# $Id: Makefile,v 1.2 2002-10-23 02:07:44 benjihan Exp $
#

SUBDIRS = display entrylist

include ../../Makefile.inc
