#
# Make image plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sasahipa.com>
#
#
# $Id: Makefile,v 1.2 2002-12-15 02:31:45 ben Exp $
#

SUBDIRS = tga jpeg

include ../../Makefile.inc
