#
# Make input plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sasahipa.com>
#
#
# $Id: Makefile,v 1.14 2004-07-04 14:16:45 vincentp Exp $
#

SUBDIRS = xing sidplay ogg mikmod sndtst sc68 spc nsf

#SUBDIRS +=  cdda

include ../../Makefile.inc
