#
# Make input plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sasahipa.com>
#
#
# $Id: Makefile,v 1.5 2002-09-14 00:47:13 zig Exp $
#

SUBDIRS = xing spc sidplay

include ../../Makefile.inc
