#
# Make input plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sasahipa.com>
#
#
# $Id: Makefile,v 1.6 2002-09-20 01:24:36 vincentp Exp $
#

SUBDIRS = xing spc sidplay ogg

include ../../Makefile.inc
