# dcplaya - mikmod - driver - Makefile
#
# $Id: Makefile,v 1.1 2002-09-21 09:53:43 benjihan Exp $ 

#LIBRARY=yes
OBJS = drv_dcplaya.o drv_nos.o

KOS_LOCAL_INCS = -I. -I../../../../../include
KOS_INCS = -I../include

OPTIMIZE = $(OPTIMIZE_FOR_SPEED)

include ../../../../../Makefile.inc
