# dcplaya - mikmod - playercode - Makefile
#
# $Id: Makefile,v 1.1 2002-09-21 09:53:43 benjihan Exp $ 

#LIBRARY=yes

KOS_LOCAL_INCS = -I.
KOS_INCS = -I../include
KOS_LOCAL_CFLAGS = -Dstrcasecmp=stricmp
OPTIMIZE = $(OPTIMIZE_FOR_SPEED)

include ../../../../../Makefile.inc
