LIBRARY=yes
OPTIMIZE        =  $(OPTIMIZE_FOR_SPEED)
KOS_INCS  	+= -I../include 
include ../../../../Makefile.inc

# DO NOT DELETE

bitwise.o: ../include/ogg/ogg.h ../include/ogg/os_types.h
bitwise.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
bitwise.o: ../include/ogg/config_types.h
framing.o: /home/ben/kos/include/string.h /home/ben/kos/include/unistd.h
framing.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
framing.o: /home/ben/kos/include/malloc.h ../include/ogg/ogg.h
framing.o: ../include/ogg/os_types.h ../include/ogg/config_types.h
