#
# Make visual plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sashipa.com>
#
# $Id: Makefile,v 1.1 2003-01-18 14:22:17 ben Exp $
#

LEZ=yes

KOS_LOCAL_INCS := -I. -I../../../include -I../../../libs
OPTIMIZE = $(OPTIMIZE_FOR_SPEED)

include ../../../Makefile.inc
