# $Id: Makefile,v 1.3 2002-09-12 17:57:31 ben Exp $

LIBRARY=yes

OPTIMIZE		=  $(OPTIMIZE_FOR_SPEED)
KOS_LOCAL_CFLAGS 	+= -DLAYER1 -DLAYER2 -DLAYER3
KOS_LOCAL_INCS	 	=  -I../include
include ../../../../Makefile.inc

