LIBRARY=yes

OPTIMIZE		=  $(OPTIMIZE_FOR_SPEED)
KOS_LOCAL_CFLAGS 	+= -DLAYER1 -DLAYER2 -DLAYER3
KOS_LOCAL_INCS	 	=  -I../include
include ../../../../Makefile.inc
# DO NOT DELETE

common.o: /home/ben/kos/include/ctype.h ../include/mpg123.h
common.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/unistd.h
common.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
common.o: /home/ben/kos/include/string.h /home/ben/kos/include/math.h
common.o: /home/ben/kos/include/newlib-libm-sh4/math.h
common.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
common.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
common.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
common.o: /home/ben/kos/include/newlib-libm-sh4/time.h
common.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
common.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
common.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
dct64_i386.o: ../include/mpg123.h /home/ben/kos/include/stdio.h
dct64_i386.o: /home/ben/kos/include/unistd.h
dct64_i386.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
dct64_i386.o: /home/ben/kos/include/string.h /home/ben/kos/include/math.h
dct64_i386.o: /home/ben/kos/include/newlib-libm-sh4/math.h
dct64_i386.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
dct64_i386.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
dct64_i386.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
dct64_i386.o: /home/ben/kos/include/newlib-libm-sh4/time.h
dct64_i386.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
dct64_i386.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
dct64_i386.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
decode_i386.o: /home/ben/kos/include/math.h
decode_i386.o: /home/ben/kos/include/newlib-libm-sh4/math.h
decode_i386.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
decode_i386.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
decode_i386.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
decode_i386.o: /home/ben/kos/include/newlib-libm-sh4/time.h
decode_i386.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
decode_i386.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
decode_i386.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
decode_i386.o: /home/ben/kos/include/string.h /home/ben/kos/include/unistd.h
decode_i386.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
decode_i386.o: ../include/mpg123.h /home/ben/kos/include/stdio.h
decode_i386.o: ../include/mpglib.h
interface.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/unistd.h
interface.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
interface.o: /home/ben/kos/include/malloc.h ../include/mpg123.h
interface.o: /home/ben/kos/include/string.h /home/ben/kos/include/math.h
interface.o: /home/ben/kos/include/newlib-libm-sh4/math.h
interface.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
interface.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
interface.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
interface.o: /home/ben/kos/include/newlib-libm-sh4/time.h
interface.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
interface.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
interface.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
interface.o: ../include/mpglib.h
layer1.o: ../include/mpg123.h /home/ben/kos/include/stdio.h
layer1.o: /home/ben/kos/include/unistd.h
layer1.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
layer1.o: /home/ben/kos/include/string.h /home/ben/kos/include/math.h
layer1.o: /home/ben/kos/include/newlib-libm-sh4/math.h
layer1.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
layer1.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
layer1.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
layer1.o: /home/ben/kos/include/newlib-libm-sh4/time.h
layer1.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
layer1.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
layer1.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
layer2.o: ../include/mpg123.h /home/ben/kos/include/stdio.h
layer2.o: /home/ben/kos/include/unistd.h
layer2.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
layer2.o: /home/ben/kos/include/string.h /home/ben/kos/include/math.h
layer2.o: /home/ben/kos/include/newlib-libm-sh4/math.h
layer2.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
layer2.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
layer2.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
layer2.o: /home/ben/kos/include/newlib-libm-sh4/time.h
layer2.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
layer2.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
layer2.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
layer2.o: ../include/l2tables.h
layer3.o: ../include/mpg123.h /home/ben/kos/include/stdio.h
layer3.o: /home/ben/kos/include/unistd.h
layer3.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
layer3.o: /home/ben/kos/include/string.h /home/ben/kos/include/math.h
layer3.o: /home/ben/kos/include/newlib-libm-sh4/math.h
layer3.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
layer3.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
layer3.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
layer3.o: /home/ben/kos/include/newlib-libm-sh4/time.h
layer3.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
layer3.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
layer3.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
layer3.o: ../include/mpglib.h ../include/huffman.h
tabinit.o: ../include/mpg123.h /home/ben/kos/include/stdio.h
tabinit.o: /home/ben/kos/include/unistd.h
tabinit.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
tabinit.o: /home/ben/kos/include/string.h /home/ben/kos/include/math.h
tabinit.o: /home/ben/kos/include/newlib-libm-sh4/math.h
tabinit.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
tabinit.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
tabinit.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
tabinit.o: /home/ben/kos/include/newlib-libm-sh4/time.h
tabinit.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
tabinit.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
tabinit.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
