#
# Make input plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sasahipa.com>
#
#
# $Id: Makefile,v 1.1 2002-09-21 09:53:43 benjihan Exp $
#

LIBRARY=yes
SUBDIRS=loaders drivers playercode mmio
OBJS = $(shell find . -name '*.o')

OPTIMIZE = $(OPTIMIZE_FOR_SPEED)

include ../../../../Makefile.inc
