#
# Make visual plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sashipa.com>
#
# $Id: Makefile,v 1.1 2002-09-03 02:13:08 ben Exp $
#

LEFS=$(shell basename `pwd`).lef

KOS_LOCAL_INCS := -I../../../include
OPTIMIZE = $(OPTIMIZE_FOR_SPEED)

include ../../../Makefile.inc
