LIBRARY=yes
OPTIMIZE		= $(OPTIMIZE_FOR_SIZE)
KOS_LOCAL_INCS		= -I../../../../include
include ../../../../Makefile.inc

# DO NOT DELETE

compat.o: global.h /home/ben/kos/include/stdlib.h
compat.o: /home/ben/kos/include/unistd.h
compat.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
compat.o: /home/ben/kos/include/malloc.h /home/ben/kos/include/string.h
compat.o: id3tag.h compat.h frame.h field.h parse.h ucs4.h
crc.o: global.h id3tag.h crc.h
debug.o: global.h /home/ben/kos/include/stdio.h
debug.o: /home/ben/kos/include/unistd.h
debug.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
debug.o: /home/ben/kos/include/stdlib.h /home/ben/kos/include/malloc.h
debug.o: /home/ben/kos/include/string.h debug.h
field.o: global.h /home/ben/kos/include/stdlib.h
field.o: /home/ben/kos/include/unistd.h
field.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
field.o: /home/ben/kos/include/malloc.h /home/ben/kos/include/string.h
field.o: id3tag.h field.h render.h ucs4.h latin1.h parse.h
file.o: global.h /home/ben/kos/include/stdlib.h
file.o: /home/ben/kos/include/unistd.h
file.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
file.o: /home/ben/kos/include/malloc.h /home/ben/kos/include/string.h
file.o: ../../../../include/file_wrapper.h id3tag.h file.h tag.h field.h
frame.o: global.h /home/ben/kos/include/stdlib.h
frame.o: /home/ben/kos/include/unistd.h
frame.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
frame.o: /home/ben/kos/include/malloc.h /home/ben/kos/include/string.h
frame.o: id3tag.h frame.h frametype.h compat.h field.h render.h parse.h
frame.o: util.h
frametype.o: global.h /home/ben/kos/include/string.h
frametype.o: /home/ben/kos/include/unistd.h
frametype.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
frametype.o: id3tag.h frametype.h
genre.o: global.h id3tag.h ucs4.h genre.dat
latin1.o: global.h /home/ben/kos/include/stdlib.h
latin1.o: /home/ben/kos/include/unistd.h
latin1.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
latin1.o: /home/ben/kos/include/malloc.h id3tag.h latin1.h ucs4.h
parse.o: global.h /home/ben/kos/include/stdlib.h
parse.o: /home/ben/kos/include/unistd.h
parse.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
parse.o: /home/ben/kos/include/malloc.h /home/ben/kos/include/string.h
parse.o: id3tag.h parse.h latin1.h utf16.h utf8.h
render.o: global.h /home/ben/kos/include/string.h
render.o: /home/ben/kos/include/unistd.h
render.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
render.o: /home/ben/kos/include/stdlib.h /home/ben/kos/include/malloc.h
render.o: id3tag.h render.h ucs4.h latin1.h utf16.h utf8.h
tag.o: global.h /home/ben/kos/include/string.h /home/ben/kos/include/unistd.h
tag.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
tag.o: /home/ben/kos/include/stdlib.h /home/ben/kos/include/malloc.h id3tag.h
tag.o: tag.h frame.h compat.h parse.h render.h latin1.h ucs4.h crc.h field.h
tag.o: util.h
ucs4.o: global.h /home/ben/kos/include/stdlib.h
ucs4.o: /home/ben/kos/include/unistd.h
ucs4.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
ucs4.o: /home/ben/kos/include/malloc.h id3tag.h ucs4.h latin1.h utf16.h
ucs4.o: utf8.h
utf16.o: global.h /home/ben/kos/include/stdlib.h
utf16.o: /home/ben/kos/include/unistd.h
utf16.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
utf16.o: /home/ben/kos/include/malloc.h id3tag.h utf16.h ucs4.h
utf8.o: global.h /home/ben/kos/include/stdlib.h
utf8.o: /home/ben/kos/include/unistd.h
utf8.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
utf8.o: /home/ben/kos/include/malloc.h id3tag.h utf8.h ucs4.h
util.o: global.h /home/ben/kos/include/stdlib.h
util.o: /home/ben/kos/include/unistd.h
util.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
util.o: /home/ben/kos/include/malloc.h id3tag.h util.h
version.o: global.h id3tag.h version.h
