LIBRARY=yes

OBJS = cdct.o csbt.o cup.o cupl3.o
OBJS += cwinm.o dec8.o hwin.o icdct.o isbt.o
OBJS += iup.o iwinm.o l3dq.o l3init.o
OBJS += mdct.o mhead.o msis.o uph.o upsf.o

OPTIMIZE 		= $(OPTIMIZE_FOR_SPEED)
KOS_LOCAL_CFLAGS 	= -DLITTLE_ENDIAN=1
KOS_LOCAL_INCS		= -I../include 

include ../../../../Makefile.inc

# DO NOT DELETE

cdct.o: /home/ben/kos/include/math.h
cdct.o: /home/ben/kos/include/newlib-libm-sh4/math.h
cdct.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
cdct.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
cdct.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
cdct.o: /home/ben/kos/include/newlib-libm-sh4/time.h
cdct.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
cdct.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
cdct.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
cdct.o: ../include/L3.h ../include/mhead.h ../include/itype.h
csbt.o: /home/ben/kos/include/math.h
csbt.o: /home/ben/kos/include/newlib-libm-sh4/math.h
csbt.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
csbt.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
csbt.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
csbt.o: /home/ben/kos/include/newlib-libm-sh4/time.h
csbt.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
csbt.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
csbt.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
csbt.o: ../include/L3.h ../include/mhead.h ../include/itype.h csbtb.c
csbt.o: csbtL3.c
cup.o: /home/ben/kos/include/math.h
cup.o: /home/ben/kos/include/newlib-libm-sh4/math.h
cup.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
cup.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
cup.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
cup.o: /home/ben/kos/include/newlib-libm-sh4/time.h
cup.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
cup.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
cup.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h ../include/L3.h
cup.o: ../include/mhead.h ../include/itype.h cupini.c cupL1.c
cupl3.o: /home/ben/kos/include/math.h
cupl3.o: /home/ben/kos/include/newlib-libm-sh4/math.h
cupl3.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
cupl3.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
cupl3.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
cupl3.o: /home/ben/kos/include/newlib-libm-sh4/time.h
cupl3.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
cupl3.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
cupl3.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
cupl3.o: /home/ben/kos/include/string.h /home/ben/kos/include/unistd.h
cupl3.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
cupl3.o: ../include/L3.h ../include/mhead.h ../include/itype.h
cupl3.o: ../include/jdw.h ../include/protos.h
cwinm.o: /home/ben/kos/include/math.h
cwinm.o: /home/ben/kos/include/newlib-libm-sh4/math.h
cwinm.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
cwinm.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
cwinm.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
cwinm.o: /home/ben/kos/include/newlib-libm-sh4/time.h
cwinm.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
cwinm.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
cwinm.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
cwinm.o: ../include/tableawd.h cwin.c ../include/mhead.h ../include/L3.h
cwinm.o: ../include/itype.h cwinb.c
dec8.o: /home/ben/kos/include/math.h
dec8.o: /home/ben/kos/include/newlib-libm-sh4/math.h
dec8.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
dec8.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
dec8.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
dec8.o: /home/ben/kos/include/newlib-libm-sh4/time.h
dec8.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
dec8.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
dec8.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
dec8.o: ../include/L3.h ../include/mhead.h ../include/itype.h
hwin.o: /home/ben/kos/include/math.h
hwin.o: /home/ben/kos/include/newlib-libm-sh4/math.h
hwin.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
hwin.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
hwin.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
hwin.o: /home/ben/kos/include/newlib-libm-sh4/time.h
hwin.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
hwin.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
hwin.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
hwin.o: ../include/L3.h ../include/mhead.h ../include/itype.h
icdct.o: /home/ben/kos/include/math.h
icdct.o: /home/ben/kos/include/newlib-libm-sh4/math.h
icdct.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
icdct.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
icdct.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
icdct.o: /home/ben/kos/include/newlib-libm-sh4/time.h
icdct.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
icdct.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
icdct.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
icdct.o: ../include/itype.h
isbt.o: /home/ben/kos/include/math.h
isbt.o: /home/ben/kos/include/newlib-libm-sh4/math.h
isbt.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
isbt.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
isbt.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
isbt.o: /home/ben/kos/include/newlib-libm-sh4/time.h
isbt.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
isbt.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
isbt.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
isbt.o: ../include/itype.h ../include/tableawd.h isbtb.c
iup.o: /home/ben/kos/include/string.h /home/ben/kos/include/unistd.h
iup.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
iup.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/math.h
iup.o: /home/ben/kos/include/newlib-libm-sh4/math.h
iup.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
iup.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
iup.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
iup.o: /home/ben/kos/include/newlib-libm-sh4/time.h
iup.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
iup.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
iup.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h ../include/L3.h
iup.o: ../include/mhead.h ../include/itype.h ../include/jdw.h iupini.c
iup.o: iupL1.c
iwinm.o: /home/ben/kos/include/math.h
iwinm.o: /home/ben/kos/include/newlib-libm-sh4/math.h
iwinm.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
iwinm.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
iwinm.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
iwinm.o: /home/ben/kos/include/newlib-libm-sh4/time.h
iwinm.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
iwinm.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
iwinm.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
iwinm.o: ../include/itype.h iwinQ.c iwinbQ.c
l3dq.o: /home/ben/kos/include/math.h
l3dq.o: /home/ben/kos/include/newlib-libm-sh4/math.h
l3dq.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
l3dq.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
l3dq.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
l3dq.o: /home/ben/kos/include/newlib-libm-sh4/time.h
l3dq.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
l3dq.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
l3dq.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
l3dq.o: /home/ben/kos/include/string.h /home/ben/kos/include/unistd.h
l3dq.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
l3dq.o: ../include/L3.h ../include/mhead.h ../include/itype.h
l3dq.o: ../include/protos.h
l3init.o: /home/ben/kos/include/math.h
l3init.o: /home/ben/kos/include/newlib-libm-sh4/math.h
l3init.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
l3init.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
l3init.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
l3init.o: /home/ben/kos/include/newlib-libm-sh4/time.h
l3init.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
l3init.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
l3init.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
l3init.o: ../include/L3.h ../include/mhead.h ../include/itype.h
l3init.o: ../include/protos.h
mdct.o: /home/ben/kos/include/math.h
mdct.o: /home/ben/kos/include/newlib-libm-sh4/math.h
mdct.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
mdct.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
mdct.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
mdct.o: /home/ben/kos/include/newlib-libm-sh4/time.h
mdct.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
mdct.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
mdct.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
mhead.o: /home/ben/kos/include/math.h
mhead.o: /home/ben/kos/include/newlib-libm-sh4/math.h
mhead.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
mhead.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
mhead.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
mhead.o: /home/ben/kos/include/newlib-libm-sh4/time.h
mhead.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
mhead.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
mhead.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
mhead.o: ../include/L3.h ../include/mhead.h ../include/itype.h
msis.o: /home/ben/kos/include/math.h
msis.o: /home/ben/kos/include/newlib-libm-sh4/math.h
msis.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
msis.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
msis.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
msis.o: /home/ben/kos/include/newlib-libm-sh4/time.h
msis.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
msis.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
msis.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
msis.o: ../include/L3.h ../include/mhead.h ../include/itype.h
uph.o: /home/ben/kos/include/math.h
uph.o: /home/ben/kos/include/newlib-libm-sh4/math.h
uph.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
uph.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
uph.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
uph.o: /home/ben/kos/include/newlib-libm-sh4/time.h
uph.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
uph.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
uph.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h ../include/L3.h
uph.o: ../include/mhead.h ../include/itype.h ../include/htable.h
upsf.o: /home/ben/kos/include/math.h
upsf.o: /home/ben/kos/include/newlib-libm-sh4/math.h
upsf.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
upsf.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
upsf.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
upsf.o: /home/ben/kos/include/newlib-libm-sh4/time.h
upsf.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
upsf.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
upsf.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
upsf.o: ../include/L3.h ../include/mhead.h ../include/itype.h
