#
# Make visual plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sasahipa.com>
#
# $Id: Makefile,v 1.1.1.1 2002-08-26 14:14:59 ben Exp $
#

SUBDIRS = fftvlr

include ../../Makefile.inc
# DO NOT DELETE
