#
# Make visual plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sasahipa.com>
#
# $Id: Makefile,v 1.7 2003-01-18 14:22:17 ben Exp $
#

SUBDIRS = fftvlr lpo hyperpipe fime

include ../../Makefile.inc
