#
# Make visual plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sasahipa.com>
#
# $Id: Makefile,v 1.3 2002-09-02 19:14:16 ben Exp $
#

SUBDIRS = fftvlr lpo

include ../../Makefile.inc
