# Makefile for dcplaya draw library
# 
# (c)2002 Ben(jamin) Gerard <ben@sashipa.com>
#
# $Id: Makefile,v 1.1 2002-11-25 16:42:28 ben Exp $

OPTIMIZE=$(OPTIMIZE_FOR_SPEED)
LIBRARY=yes
KOS_LOCAL_INCS = -I.. -I../../include
KOS_LOCAL_CFLAGS =

include ../../Makefile.inc
