# Main application Makefile for Dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard
#
# $Id: Makefile,v 1.2 2002-08-26 20:12:22 ben Exp $

LIBNAME=libdreammp3.a
OPTIMIZE = $(OPTIMIZE_FOR_SPEED)

TOPDIR:=$(dir $(shell pwd))

KOS_LOCAL_INCS := -I../include -I..

KOS_LOCAL_CFLAGS += -DDREAMMP3_HOME="\"$(TOPDIR)\""

include ../Makefile.inc
# DO NOT DELETE

3dutils.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/unistd.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
3dutils.o: ../include/gp.h /home/ben/kos/include/kos.h
3dutils.o: /home/ben/kos/include/ctype.h /home/ben/kos/include/malloc.h
3dutils.o: /home/ben/kos/include/string.h /home/ben/kos/include/kos/fs.h
3dutils.o: /home/ben/kos/include/kos/limits.h
3dutils.o: /home/ben/kos/include/kos/fs_builtin.h
3dutils.o: /home/ben/kos/include/kos/fs_romdisk.h
3dutils.o: /home/ben/kos/include/kos/pcx.h /home/ben/kos/include/kos/thread.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/irq.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/arch.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/video.h
3dutils.o: /home/ben/kos/include/sys/queue.h
3dutils.o: /home/ben/kos/include/sys/iovec.h /home/ben/kos/include/kos/sem.h
3dutils.o: /home/ben/kos/include/kos/cond.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/cache.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/dbgio.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/spinlock.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/syscall.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/timer.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/biosfont.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/cdrom.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/controller.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_dcload.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_iso9660.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_vmu.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/g2.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/keyboard.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/maple.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/mouse.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/spu.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/ta.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/vmu.h
3dutils.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fmath.h
3dutils.o: /home/ben/kos/include/os/process.h /home/ben/kos/include/os/elf.h
3dutils.o: /home/ben/kos/include/os/svcmpx.h
3dutils.o: /home/ben/kos/include/dcutils/3dutils.h
3dutils.o: /home/ben/kos/include/dcutils/matrix.h
3dutils.o: /home/ben/kos/include/dcutils/bspline.h
3dutils.o: /home/ben/kos/include/dcutils/pcx.h
3dutils.o: /home/ben/kos/include/dcutils/precompiler.h
3dutils.o: /home/ben/kos/include/dcutils/pvrutils.h ../include/sintab.h
bkg.o: ../include/gp.h /home/ben/kos/include/kos.h
bkg.o: /home/ben/kos/include/ctype.h /home/ben/kos/include/malloc.h
bkg.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/unistd.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
bkg.o: /home/ben/kos/include/string.h /home/ben/kos/include/kos/fs.h
bkg.o: /home/ben/kos/include/kos/limits.h
bkg.o: /home/ben/kos/include/kos/fs_builtin.h
bkg.o: /home/ben/kos/include/kos/fs_romdisk.h /home/ben/kos/include/kos/pcx.h
bkg.o: /home/ben/kos/include/kos/thread.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/irq.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/arch.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/video.h
bkg.o: /home/ben/kos/include/sys/queue.h /home/ben/kos/include/sys/iovec.h
bkg.o: /home/ben/kos/include/kos/sem.h /home/ben/kos/include/kos/cond.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/cache.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/dbgio.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/spinlock.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/syscall.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/timer.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/biosfont.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/cdrom.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/controller.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_dcload.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_iso9660.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_vmu.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/g2.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/keyboard.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/maple.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/mouse.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/spu.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/ta.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/vmu.h
bkg.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fmath.h
bkg.o: /home/ben/kos/include/os/process.h /home/ben/kos/include/os/elf.h
bkg.o: /home/ben/kos/include/os/svcmpx.h
bkg.o: /home/ben/kos/include/dcutils/3dutils.h
bkg.o: /home/ben/kos/include/dcutils/matrix.h
bkg.o: /home/ben/kos/include/dcutils/bspline.h
bkg.o: /home/ben/kos/include/dcutils/pcx.h
bkg.o: /home/ben/kos/include/dcutils/precompiler.h
bkg.o: /home/ben/kos/include/dcutils/pvrutils.h
border.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/unistd.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
border.o: ../include/gp.h /home/ben/kos/include/kos.h
border.o: /home/ben/kos/include/ctype.h /home/ben/kos/include/malloc.h
border.o: /home/ben/kos/include/string.h /home/ben/kos/include/kos/fs.h
border.o: /home/ben/kos/include/kos/limits.h
border.o: /home/ben/kos/include/kos/fs_builtin.h
border.o: /home/ben/kos/include/kos/fs_romdisk.h
border.o: /home/ben/kos/include/kos/pcx.h /home/ben/kos/include/kos/thread.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/irq.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/arch.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/video.h
border.o: /home/ben/kos/include/sys/queue.h /home/ben/kos/include/sys/iovec.h
border.o: /home/ben/kos/include/kos/sem.h /home/ben/kos/include/kos/cond.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/cache.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/dbgio.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/spinlock.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/syscall.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/timer.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/biosfont.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/cdrom.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/controller.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_dcload.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_iso9660.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_vmu.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/g2.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/keyboard.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/maple.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/mouse.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/spu.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/ta.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/vmu.h
border.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fmath.h
border.o: /home/ben/kos/include/os/process.h /home/ben/kos/include/os/elf.h
border.o: /home/ben/kos/include/os/svcmpx.h
border.o: /home/ben/kos/include/dcutils/3dutils.h
border.o: /home/ben/kos/include/dcutils/matrix.h
border.o: /home/ben/kos/include/dcutils/bspline.h
border.o: /home/ben/kos/include/dcutils/pcx.h
border.o: /home/ben/kos/include/dcutils/precompiler.h
border.o: /home/ben/kos/include/dcutils/pvrutils.h
controler.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/unistd.h
controler.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
controler.o: /home/ben/kos/include/kos/thread.h
controler.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/irq.h
controler.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/arch.h
controler.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/video.h
controler.o: /home/ben/kos/include/sys/queue.h
controler.o: /home/ben/kos/include/sys/iovec.h
controler.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/spinlock.h
controler.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/maple.h
controler.o: ../include/controler.h
controler.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/controller.h
dreamcast68.o: ../include/config.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fmath.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
dreamcast68.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/unistd.h
dreamcast68.o: ../include/sndstream.h ../include/songmenu.h ../include/gp.h
dreamcast68.o: /home/ben/kos/include/kos.h /home/ben/kos/include/ctype.h
dreamcast68.o: /home/ben/kos/include/malloc.h /home/ben/kos/include/string.h
dreamcast68.o: /home/ben/kos/include/kos/fs.h
dreamcast68.o: /home/ben/kos/include/kos/limits.h
dreamcast68.o: /home/ben/kos/include/kos/fs_builtin.h
dreamcast68.o: /home/ben/kos/include/kos/fs_romdisk.h
dreamcast68.o: /home/ben/kos/include/kos/pcx.h
dreamcast68.o: /home/ben/kos/include/kos/thread.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/irq.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/arch.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/video.h
dreamcast68.o: /home/ben/kos/include/sys/queue.h
dreamcast68.o: /home/ben/kos/include/sys/iovec.h
dreamcast68.o: /home/ben/kos/include/kos/sem.h
dreamcast68.o: /home/ben/kos/include/kos/cond.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/cache.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/dbgio.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/spinlock.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/syscall.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/timer.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/biosfont.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/cdrom.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/controller.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_dcload.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_iso9660.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_vmu.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/g2.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/keyboard.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/maple.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/mouse.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/spu.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/ta.h
dreamcast68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/vmu.h
dreamcast68.o: /home/ben/kos/include/os/process.h
dreamcast68.o: /home/ben/kos/include/os/elf.h
dreamcast68.o: /home/ben/kos/include/os/svcmpx.h
dreamcast68.o: /home/ben/kos/include/dcutils/3dutils.h
dreamcast68.o: /home/ben/kos/include/dcutils/matrix.h
dreamcast68.o: /home/ben/kos/include/dcutils/bspline.h
dreamcast68.o: /home/ben/kos/include/dcutils/pcx.h
dreamcast68.o: /home/ben/kos/include/dcutils/precompiler.h
dreamcast68.o: /home/ben/kos/include/dcutils/pvrutils.h
dreamcast68.o: ../include/file_wrapper.h ../include/matrix.h
dreamcast68.o: ../include/obj3d.h ../include/controler.h ../include/info.h
dreamcast68.o: ../include/option.h ../include/remanens.h ../include/playa.h
dreamcast68.o: ../include/playa_info.h ../include/vupeek.h
dreamcast68.o: ../include/driver_list.h ../include/any_driver.h
dreamcast68.o: ../include/driver_option.h ../include/inp_driver.h
dreamcast68.o: ../include/plugin.h ../include/lef.h ../include/fft.h
dreamcast68.o: ../include/int_fft.h
driver_list.o: /home/ben/kos/include/string.h /home/ben/kos/include/unistd.h
driver_list.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
driver_list.o: ../include/driver_list.h ../include/any_driver.h
driver_list.o: ../include/driver_option.h ../include/inp_driver.h
driver_list.o: ../include/playa_info.h ../include/filetype.h
entrylist.o: /home/ben/kos/include/kos.h /home/ben/kos/include/ctype.h
entrylist.o: /home/ben/kos/include/malloc.h /home/ben/kos/include/stdio.h
entrylist.o: /home/ben/kos/include/unistd.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
entrylist.o: /home/ben/kos/include/string.h /home/ben/kos/include/kos/fs.h
entrylist.o: /home/ben/kos/include/kos/limits.h
entrylist.o: /home/ben/kos/include/kos/fs_builtin.h
entrylist.o: /home/ben/kos/include/kos/fs_romdisk.h
entrylist.o: /home/ben/kos/include/kos/pcx.h
entrylist.o: /home/ben/kos/include/kos/thread.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/irq.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/arch.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/video.h
entrylist.o: /home/ben/kos/include/sys/queue.h
entrylist.o: /home/ben/kos/include/sys/iovec.h
entrylist.o: /home/ben/kos/include/kos/sem.h /home/ben/kos/include/kos/cond.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/cache.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/dbgio.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/spinlock.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/syscall.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/timer.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/biosfont.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/cdrom.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/controller.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_dcload.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_iso9660.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_vmu.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/g2.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/keyboard.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/maple.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/mouse.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/spu.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/ta.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/vmu.h
entrylist.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fmath.h
entrylist.o: /home/ben/kos/include/os/process.h
entrylist.o: /home/ben/kos/include/os/elf.h /home/ben/kos/include/os/svcmpx.h
entrylist.o: /home/ben/kos/include/dcutils/3dutils.h
entrylist.o: /home/ben/kos/include/dcutils/matrix.h
entrylist.o: /home/ben/kos/include/dcutils/bspline.h
entrylist.o: /home/ben/kos/include/dcutils/pcx.h
entrylist.o: /home/ben/kos/include/dcutils/precompiler.h
entrylist.o: /home/ben/kos/include/dcutils/pvrutils.h ../include/entrylist.h
fft.o: ../include/fft.h ../include/int_fft.h ../include/math_int.h
fifo.o: /home/ben/kos/include/kos.h /home/ben/kos/include/ctype.h
fifo.o: /home/ben/kos/include/malloc.h /home/ben/kos/include/stdio.h
fifo.o: /home/ben/kos/include/unistd.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
fifo.o: /home/ben/kos/include/string.h /home/ben/kos/include/kos/fs.h
fifo.o: /home/ben/kos/include/kos/limits.h
fifo.o: /home/ben/kos/include/kos/fs_builtin.h
fifo.o: /home/ben/kos/include/kos/fs_romdisk.h
fifo.o: /home/ben/kos/include/kos/pcx.h /home/ben/kos/include/kos/thread.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/irq.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/arch.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/video.h
fifo.o: /home/ben/kos/include/sys/queue.h /home/ben/kos/include/sys/iovec.h
fifo.o: /home/ben/kos/include/kos/sem.h /home/ben/kos/include/kos/cond.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/cache.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/dbgio.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/spinlock.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/syscall.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/timer.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/biosfont.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/cdrom.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/controller.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_dcload.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_iso9660.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_vmu.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/g2.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/keyboard.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/maple.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/mouse.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/spu.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/ta.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/vmu.h
fifo.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fmath.h
fifo.o: /home/ben/kos/include/os/process.h /home/ben/kos/include/os/elf.h
fifo.o: /home/ben/kos/include/os/svcmpx.h
fifo.o: /home/ben/kos/include/dcutils/3dutils.h
fifo.o: /home/ben/kos/include/dcutils/matrix.h
fifo.o: /home/ben/kos/include/dcutils/bspline.h
fifo.o: /home/ben/kos/include/dcutils/pcx.h
fifo.o: /home/ben/kos/include/dcutils/precompiler.h
fifo.o: /home/ben/kos/include/dcutils/pvrutils.h
filetype.o: /home/ben/kos/include/string.h /home/ben/kos/include/unistd.h
filetype.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
filetype.o: ../include/filetype.h
file_wrapper.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/unistd.h
file_wrapper.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
file_wrapper.o: /home/ben/kos/include/kos/fs.h
file_wrapper.o: /home/ben/kos/include/kos/limits.h ../include/file_wrapper.h
info.o: /home/ben/kos/include/kos/thread.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/irq.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/arch.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/video.h
info.o: /home/ben/kos/include/sys/queue.h /home/ben/kos/include/sys/iovec.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/spinlock.h
info.o: ../include/gp.h /home/ben/kos/include/kos.h
info.o: /home/ben/kos/include/ctype.h /home/ben/kos/include/malloc.h
info.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/unistd.h
info.o: /home/ben/kos/include/string.h /home/ben/kos/include/kos/fs.h
info.o: /home/ben/kos/include/kos/limits.h
info.o: /home/ben/kos/include/kos/fs_builtin.h
info.o: /home/ben/kos/include/kos/fs_romdisk.h
info.o: /home/ben/kos/include/kos/pcx.h /home/ben/kos/include/kos/sem.h
info.o: /home/ben/kos/include/kos/cond.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/cache.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/dbgio.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/syscall.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/timer.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/biosfont.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/cdrom.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/controller.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_dcload.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_iso9660.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_vmu.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/g2.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/keyboard.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/maple.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/mouse.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/spu.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/ta.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/vmu.h
info.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fmath.h
info.o: /home/ben/kos/include/os/process.h /home/ben/kos/include/os/elf.h
info.o: /home/ben/kos/include/os/svcmpx.h
info.o: /home/ben/kos/include/dcutils/3dutils.h
info.o: /home/ben/kos/include/dcutils/matrix.h
info.o: /home/ben/kos/include/dcutils/bspline.h
info.o: /home/ben/kos/include/dcutils/pcx.h
info.o: /home/ben/kos/include/dcutils/precompiler.h
info.o: /home/ben/kos/include/dcutils/pvrutils.h ../include/info.h
info.o: ../include/controler.h ../include/songmenu.h ../include/playa_info.h
lef.o: /home/ben/kos/include/malloc.h /home/ben/kos/include/string.h
lef.o: /home/ben/kos/include/unistd.h
lef.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
lef.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/kos/fs.h
lef.o: /home/ben/kos/include/kos/limits.h ../include/lef.h
lef.o: /home/ben/kos/include/sys/queue.h
m3u.o: ../include/m3u.h
math_int.o: ../include/math_int.h
matrix.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fmath.h
matrix.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
matrix.o: ../include/matrix.h
obj3d.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/unistd.h
obj3d.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
obj3d.o: /home/ben/kos/include/math.h
obj3d.o: /home/ben/kos/include/newlib-libm-sh4/math.h
obj3d.o: /home/ben/kos/include/newlib-libm-sh4/sys/reent.h
obj3d.o: /home/ben/kos/include/newlib-libm-sh4/_ansi.h
obj3d.o: /home/ben/kos/include/newlib-libm-sh4/sys/config.h
obj3d.o: /home/ben/kos/include/newlib-libm-sh4/time.h
obj3d.o: /home/ben/kos/include/newlib-libm-sh4/machine/time.h
obj3d.o: /home/ben/kos/include/newlib-libm-sh4/machine/types.h
obj3d.o: /home/ben/kos/include/newlib-libm-sh4/machine/ieeefp.h
obj3d.o: /home/ben/kos/include/malloc.h ../include/obj_driver.h
obj3d.o: ../include/any_driver.h ../include/driver_option.h
obj3d.o: ../include/obj3d.h ../include/matrix.h
option.o: ../include/config.h ../include/gp.h /home/ben/kos/include/kos.h
option.o: /home/ben/kos/include/ctype.h /home/ben/kos/include/malloc.h
option.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/unistd.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
option.o: /home/ben/kos/include/string.h /home/ben/kos/include/kos/fs.h
option.o: /home/ben/kos/include/kos/limits.h
option.o: /home/ben/kos/include/kos/fs_builtin.h
option.o: /home/ben/kos/include/kos/fs_romdisk.h
option.o: /home/ben/kos/include/kos/pcx.h /home/ben/kos/include/kos/thread.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/irq.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/arch.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/video.h
option.o: /home/ben/kos/include/sys/queue.h /home/ben/kos/include/sys/iovec.h
option.o: /home/ben/kos/include/kos/sem.h /home/ben/kos/include/kos/cond.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/cache.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/dbgio.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/spinlock.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/syscall.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/timer.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/biosfont.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/cdrom.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/controller.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_dcload.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_iso9660.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_vmu.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/g2.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/keyboard.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/maple.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/mouse.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/spu.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/ta.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/vmu.h
option.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fmath.h
option.o: /home/ben/kos/include/os/process.h /home/ben/kos/include/os/elf.h
option.o: /home/ben/kos/include/os/svcmpx.h
option.o: /home/ben/kos/include/dcutils/3dutils.h
option.o: /home/ben/kos/include/dcutils/matrix.h
option.o: /home/ben/kos/include/dcutils/bspline.h
option.o: /home/ben/kos/include/dcutils/pcx.h
option.o: /home/ben/kos/include/dcutils/precompiler.h
option.o: /home/ben/kos/include/dcutils/pvrutils.h ../include/option.h
option.o: ../include/controler.h ../include/file_wrapper.h
pcm_buffer.o: /home/ben/kos/include/stdlib.h /home/ben/kos/include/unistd.h
pcm_buffer.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
pcm_buffer.o: /home/ben/kos/include/malloc.h ../include/pcm_buffer.h
playa.o: /home/ben/kos/include/kos.h /home/ben/kos/include/ctype.h
playa.o: /home/ben/kos/include/malloc.h /home/ben/kos/include/stdio.h
playa.o: /home/ben/kos/include/unistd.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
playa.o: /home/ben/kos/include/string.h /home/ben/kos/include/kos/fs.h
playa.o: /home/ben/kos/include/kos/limits.h
playa.o: /home/ben/kos/include/kos/fs_builtin.h
playa.o: /home/ben/kos/include/kos/fs_romdisk.h
playa.o: /home/ben/kos/include/kos/pcx.h /home/ben/kos/include/kos/thread.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/irq.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/arch.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/video.h
playa.o: /home/ben/kos/include/sys/queue.h /home/ben/kos/include/sys/iovec.h
playa.o: /home/ben/kos/include/kos/sem.h /home/ben/kos/include/kos/cond.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/cache.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/dbgio.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/spinlock.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/syscall.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/timer.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/biosfont.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/cdrom.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/controller.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_dcload.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_iso9660.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_vmu.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/g2.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/keyboard.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/maple.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/mouse.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/spu.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/ta.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/vmu.h
playa.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fmath.h
playa.o: /home/ben/kos/include/os/process.h /home/ben/kos/include/os/elf.h
playa.o: /home/ben/kos/include/os/svcmpx.h
playa.o: /home/ben/kos/include/dcutils/3dutils.h
playa.o: /home/ben/kos/include/dcutils/matrix.h
playa.o: /home/ben/kos/include/dcutils/bspline.h
playa.o: /home/ben/kos/include/dcutils/pcx.h
playa.o: /home/ben/kos/include/dcutils/precompiler.h
playa.o: /home/ben/kos/include/dcutils/pvrutils.h ../include/playa.h
playa.o: ../include/playa_info.h ../include/inp_driver.h
playa.o: ../include/any_driver.h ../include/driver_option.h
playa.o: ../include/sndstream.h ../include/pcm_buffer.h
playa.o: ../include/driver_list.h ../include/file_wrapper.h ../include/fifo.h
plugin.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/unistd.h
plugin.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
plugin.o: /home/ben/kos/include/string.h /home/ben/kos/include/kos/fs.h
plugin.o: /home/ben/kos/include/kos/limits.h ../include/any_driver.h
plugin.o: ../include/driver_option.h ../include/driver_list.h
plugin.o: ../include/inp_driver.h ../include/playa_info.h ../include/lef.h
plugin.o: /home/ben/kos/include/sys/queue.h ../include/filetype.h
remanens.o: ../include/config.h ../include/remanens.h ../include/matrix.h
remanens.o: ../include/obj3d.h
sndstream.o: /home/ben/kos/include/kos.h /home/ben/kos/include/ctype.h
sndstream.o: /home/ben/kos/include/malloc.h /home/ben/kos/include/stdio.h
sndstream.o: /home/ben/kos/include/unistd.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
sndstream.o: /home/ben/kos/include/string.h /home/ben/kos/include/kos/fs.h
sndstream.o: /home/ben/kos/include/kos/limits.h
sndstream.o: /home/ben/kos/include/kos/fs_builtin.h
sndstream.o: /home/ben/kos/include/kos/fs_romdisk.h
sndstream.o: /home/ben/kos/include/kos/pcx.h
sndstream.o: /home/ben/kos/include/kos/thread.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/irq.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/arch.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/video.h
sndstream.o: /home/ben/kos/include/sys/queue.h
sndstream.o: /home/ben/kos/include/sys/iovec.h
sndstream.o: /home/ben/kos/include/kos/sem.h /home/ben/kos/include/kos/cond.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/cache.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/dbgio.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/spinlock.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/syscall.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/timer.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/biosfont.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/cdrom.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/controller.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_dcload.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_iso9660.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_vmu.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/g2.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/keyboard.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/maple.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/mouse.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/spu.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/ta.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/vmu.h
sndstream.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fmath.h
sndstream.o: /home/ben/kos/include/os/process.h
sndstream.o: /home/ben/kos/include/os/elf.h /home/ben/kos/include/os/svcmpx.h
sndstream.o: /home/ben/kos/include/dcutils/3dutils.h
sndstream.o: /home/ben/kos/include/dcutils/matrix.h
sndstream.o: /home/ben/kos/include/dcutils/bspline.h
sndstream.o: /home/ben/kos/include/dcutils/pcx.h
sndstream.o: /home/ben/kos/include/dcutils/precompiler.h
sndstream.o: /home/ben/kos/include/dcutils/pvrutils.h ../include/sndstream.h
sndstream.o: ../arm/aica_cmd_iface.h
songmenu.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/unistd.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
songmenu.o: /home/ben/kos/include/string.h ../include/gp.h
songmenu.o: /home/ben/kos/include/kos.h /home/ben/kos/include/ctype.h
songmenu.o: /home/ben/kos/include/malloc.h /home/ben/kos/include/kos/fs.h
songmenu.o: /home/ben/kos/include/kos/limits.h
songmenu.o: /home/ben/kos/include/kos/fs_builtin.h
songmenu.o: /home/ben/kos/include/kos/fs_romdisk.h
songmenu.o: /home/ben/kos/include/kos/pcx.h
songmenu.o: /home/ben/kos/include/kos/thread.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/irq.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/arch.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/video.h
songmenu.o: /home/ben/kos/include/sys/queue.h
songmenu.o: /home/ben/kos/include/sys/iovec.h /home/ben/kos/include/kos/sem.h
songmenu.o: /home/ben/kos/include/kos/cond.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/cache.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/dbgio.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/spinlock.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/syscall.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/timer.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/biosfont.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/cdrom.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/controller.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_dcload.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_iso9660.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_vmu.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/g2.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/keyboard.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/maple.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/mouse.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/spu.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/ta.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/vmu.h
songmenu.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fmath.h
songmenu.o: /home/ben/kos/include/os/process.h /home/ben/kos/include/os/elf.h
songmenu.o: /home/ben/kos/include/os/svcmpx.h
songmenu.o: /home/ben/kos/include/dcutils/3dutils.h
songmenu.o: /home/ben/kos/include/dcutils/matrix.h
songmenu.o: /home/ben/kos/include/dcutils/bspline.h
songmenu.o: /home/ben/kos/include/dcutils/pcx.h
songmenu.o: /home/ben/kos/include/dcutils/precompiler.h
songmenu.o: /home/ben/kos/include/dcutils/pvrutils.h ../include/songmenu.h
songmenu.o: ../include/entrylist.h ../include/controler.h ../include/option.h
songmenu.o: ../include/m3u.h ../include/driver_list.h ../include/any_driver.h
songmenu.o: ../include/driver_option.h ../include/inp_driver.h
songmenu.o: ../include/playa_info.h ../include/filetype.h
text.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/unistd.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
text.o: ../include/gp.h /home/ben/kos/include/kos.h
text.o: /home/ben/kos/include/ctype.h /home/ben/kos/include/malloc.h
text.o: /home/ben/kos/include/string.h /home/ben/kos/include/kos/fs.h
text.o: /home/ben/kos/include/kos/limits.h
text.o: /home/ben/kos/include/kos/fs_builtin.h
text.o: /home/ben/kos/include/kos/fs_romdisk.h
text.o: /home/ben/kos/include/kos/pcx.h /home/ben/kos/include/kos/thread.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/irq.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/arch.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/video.h
text.o: /home/ben/kos/include/sys/queue.h /home/ben/kos/include/sys/iovec.h
text.o: /home/ben/kos/include/kos/sem.h /home/ben/kos/include/kos/cond.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/cache.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/dbgio.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/spinlock.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/syscall.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/timer.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/biosfont.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/cdrom.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/controller.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_dcload.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_iso9660.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_vmu.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/g2.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/keyboard.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/maple.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/mouse.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/spu.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/ta.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/vmu.h
text.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fmath.h
text.o: /home/ben/kos/include/os/process.h /home/ben/kos/include/os/elf.h
text.o: /home/ben/kos/include/os/svcmpx.h
text.o: /home/ben/kos/include/dcutils/3dutils.h
text.o: /home/ben/kos/include/dcutils/matrix.h
text.o: /home/ben/kos/include/dcutils/bspline.h
text.o: /home/ben/kos/include/dcutils/pcx.h
text.o: /home/ben/kos/include/dcutils/precompiler.h
text.o: /home/ben/kos/include/dcutils/pvrutils.h
viewport.o: ../include/viewport.h
vmu68.o: ../include/config.h
vmu68.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/vmu.h
vmu68.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
vmu68.o: /home/ben/kos/include/string.h /home/ben/kos/include/unistd.h
vmu68.o: /home/ben/kos/include/stdio.h ../include/playa_info.h
vmu68.o: ../include/vmu_sc68.h ../include/vmu_font.h ../include/fft.h
vmu68.o: ../include/int_fft.h ../include/vupeek.h ../include/option.h
vupeek.o: ../include/vupeek.h ../include/math_int.h
warning.o: ../include/config.h ../include/gp.h /home/ben/kos/include/kos.h
warning.o: /home/ben/kos/include/ctype.h /home/ben/kos/include/malloc.h
warning.o: /home/ben/kos/include/stdio.h /home/ben/kos/include/unistd.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/types.h
warning.o: /home/ben/kos/include/string.h /home/ben/kos/include/kos/fs.h
warning.o: /home/ben/kos/include/kos/limits.h
warning.o: /home/ben/kos/include/kos/fs_builtin.h
warning.o: /home/ben/kos/include/kos/fs_romdisk.h
warning.o: /home/ben/kos/include/kos/pcx.h /home/ben/kos/include/kos/thread.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/irq.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/arch.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/video.h
warning.o: /home/ben/kos/include/sys/queue.h
warning.o: /home/ben/kos/include/sys/iovec.h /home/ben/kos/include/kos/sem.h
warning.o: /home/ben/kos/include/kos/cond.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/cache.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/dbgio.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/spinlock.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/syscall.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/arch/timer.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/biosfont.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/cdrom.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/controller.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_dcload.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_iso9660.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fs_vmu.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/g2.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/keyboard.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/maple.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/mouse.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/spu.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/ta.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/vmu.h
warning.o: /home/ben/kos/kernel/arch/dreamcast/include/dc/fmath.h
warning.o: /home/ben/kos/include/os/process.h /home/ben/kos/include/os/elf.h
warning.o: /home/ben/kos/include/os/svcmpx.h
warning.o: /home/ben/kos/include/dcutils/3dutils.h
warning.o: /home/ben/kos/include/dcutils/matrix.h
warning.o: /home/ben/kos/include/dcutils/bspline.h
warning.o: /home/ben/kos/include/dcutils/pcx.h
warning.o: /home/ben/kos/include/dcutils/precompiler.h
warning.o: /home/ben/kos/include/dcutils/pvrutils.h
