#
# Make visual plugins for dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard <ben@sashipa.com>
#
# $Id: Makefile,v 1.3 2002-11-25 16:56:09 ben Exp $
#

LEZ=yes

KOS_LOCAL_INCS := -I. -I../../../include -I../../../libs

OPTIMIZE = $(OPTIMIZE_FOR_SPEED)

include ../../../Makefile.inc
