LIBRARY=yes
SUBDIRS= SHAblitter SHAR SHAtk SHAtranslator SHAwrapper
KOS_LOCAL_INCS = -I.. -I../../include

LIB_EXTRA := \
 ./SHAtk/SHAstreamFile.o\
 ./SHAtk/SHAstreamMem.o\
 ./SHAR/SHARimg.o\
 ./SHAwrapper/SHAwrapper.o\
 ./SHAtranslator/SHAtranslator.o\
 ./SHAtranslator/SHAtranslatorImage.o\
 ./SHAtranslator/SHAtranslatorBlitter.o\
 ./SHAtranslator/SHAtranslatorResult.o\
 ./SHAblitter/SHAblitter.o\
 ./SHAblitter/SHAblitterFastCopy.o\
 ./SHAblitter/SHAblitterFastStretch.o

include ../../Makefile.inc
