# Makefile for dcplaya ta library
# 
# (c)2002 Ben(jamin) Gerard <ben@sashipa.com>
#
# $Id: Makefile,v 1.1 2004-07-04 14:16:45 vincentp Exp $

OPTIMIZE=$(OPTIMIZE_FOR_SPEED)
LIBRARY=yes
KOS_LOCAL_INCS = -I.. -I../../include
KOS_LOCAL_CFLAGS =

include ../../Makefile.inc
